import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const courses = [
  // PRE-SEA
  { slug: "pre-sea-deck-cadet", title: "Pre-Sea Deck Cadet Programme", stcwRegulation: "STCW II/1", level: "PRE_SEA", durationWeeks: 26, feeNaira: 0, registrationFormType: "GOOGLE_FORM", description: "Nigeria flagship pre-sea deck officer training programme. Covers nautical science, navigation, seamanship, meteorology, GMDSS and bridge resource management. NIMASA approved, IMO STCW 2010 Manila compliant.", eligibility: "Min 5 O-Level credits including English, Maths, Physics\nAge 16-25\nValid ENG1 or ML5 medical certificate from NIMASA-approved centre\nNIN (National Identification Number)\nGood eyesight (correctable to 6/6)", outcomes: "Officer of the Watch (Deck) eligibility\nNIMASA-registered STCW II/1 certificate\nBridge watchkeeping competency\nPlacement with Nigerian and international shipping lines", nimasaApproved: true },
  { slug: "pre-sea-engineering-cadet", title: "Pre-Sea Engineering Cadet Programme", stcwRegulation: "STCW III/1", level: "PRE_SEA", durationWeeks: 26, feeNaira: 0, registrationFormType: "GOOGLE_FORM", description: "Comprehensive marine engineering cadet programme covering diesel engines, electrical systems, pumping, damage control and engineering watchkeeping. NIMASA approved, STCW III/1 compliant.", eligibility: "Min 5 O-Level credits including English, Maths, Physics and Technical Drawing\nAge 16-25\nValid ENG1 or ML5 medical certificate\nNIN required", outcomes: "Officer of the Watch (Engine) eligibility\nNIMASA-registered STCW III/1 certificate\nEngine room watchkeeping competency\nNNPC and international shipping line placements available", nimasaApproved: true },
  // BASIC STCW SAFETY TRAINING
  { slug: "basic-safety-training", title: "Basic Safety Training (BST)", stcwRegulation: "STCW VI/1", level: "SHORT_COURSE", durationWeeks: 4, feeNaira: 0, registrationFormType: "MS_FORM", description: "The mandatory STCW basic safety package required for all seafarers. Covers personal survival techniques, fire prevention and fire-fighting, elementary first aid, and personal safety and social responsibilities.", eligibility: "Open to all persons seeking employment at sea\nMinimum age 16\nBasic literacy and numeracy\nMedical fitness certificate", outcomes: "STCW VI/1 certificate (mandatory for all seafarers)\nNIMASA-registered certification\nPersonal Survival Techniques\nFire Prevention and Fire Fighting\nElementary First Aid", nimasaApproved: true },
  { slug: "security-awareness", title: "Security Awareness Training", stcwRegulation: "STCW VI/6", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "STCW VI/6 Security Awareness training for all crew without designated security duties. Covers ISPS Code, recognising security threats and reporting procedures.", eligibility: "All seafarers required to have security awareness training\nAge 18+\nNo prerequisites", outcomes: "STCW VI/6 Security Awareness certificate\nNIMASA-registered\nISPS Code understanding\nSecurity threat recognition", nimasaApproved: true },
  { slug: "bst-refresher", title: "BST Refresher Course", stcwRegulation: "STCW VI/1", level: "REFRESHER", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "5-year refresher for seafarers revalidating their Basic Safety Training certificate. Covers updated STCW Manila amendments, revised fire-fighting drills and updated survival techniques.", eligibility: "Existing BST certificate holder\nCertificate due for revalidation within 12 months or expired within 5 years\nMedical certificate", outcomes: "BST Revalidation endorsement\nNIMASA-registered\nUpdated STCW Manila competencies", nimasaApproved: true },
  // OTHER BASIC STCW
  { slug: "gmdss-general-operator", title: "GMDSS General Operator Certificate", stcwRegulation: "STCW IV/2", level: "SHORT_COURSE", durationWeeks: 4, feeNaira: 0, registrationFormType: "MS_FORM", description: "The GMDSS GOC qualifies officers to operate all GMDSS equipment including EPIRB, SART, VHF, MF/HF DSC, NAVTEX and Inmarsat systems on SOLAS vessels. IMO Model Course 1.25.", eligibility: "O-Level passes in English, Mathematics and Physics\nAge 18+\nMedical fitness certificate", outcomes: "GMDSS General Operator Certificate\nNIMASA-registered, internationally recognised\nMF/HF and VHF DSC operations\nEPIRB, SART and Inmarsat proficiency", nimasaApproved: true },
  { slug: "medical-first-aid-mfau", title: "Medical First Aid (MFAU)", stcwRegulation: "STCW VI/4.1", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "STCW VI/4.1 Medical First Aid training equips seafarers to provide immediate medical care in emergencies at sea. Covers CPR, trauma management, burns and use of a ship medical kit.", eligibility: "All seafarers required to complete medical first aid training\nAge 18+\nBasic literacy", outcomes: "STCW VI/4.1 MFAU Certificate\nNIMASA-registered\nCPR and AED competency\nTrauma and burn management\nMedical kit operation", nimasaApproved: true },
  { slug: "proficiency-survival-craft", title: "Proficiency in Survival Craft and Rescue Boats", stcwRegulation: "STCW VI/2.1", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "STCW VI/2.1 training in the use, deployment and handling of liferaft, lifeboats and rescue boats. Emergency procedures, distress signals and survivor care.", eligibility: "Seafarers required to take charge of a survival craft\nValid BST certificate preferred\nAge 18+", outcomes: "STCW VI/2.1 Certificate\nNIMASA-registered\nLiferaft and lifeboat handling\nDistress signal operation\nSurvivor recovery and care", nimasaApproved: true },
  { slug: "psc-awareness", title: "PSC Awareness (Port State Control)", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Practical training on Port State Control inspection procedures. Prepares officers and crew to pass PSC inspections by understanding deficiency categories, detainable deficiencies and PSC officer expectations.", eligibility: "Officers and ratings seeking PSC inspection readiness\nAge 18+", outcomes: "PSC readiness certificate\nDeficiency category knowledge\nDetainable deficiency avoidance\nInspection confidence", nimasaApproved: true },
  // ADVANCED STCW
  { slug: "advanced-fire-fighting", title: "Advanced Fire Fighting", stcwRegulation: "STCW VI/3", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "STCW VI/3 Advanced Fire Fighting for officers and ratings who may be required to take charge of fire-fighting operations. Live fire exercises using industry-standard equipment.", eligibility: "Valid BST certificate\nDeck or engineering officer or rating\nAge 18+", outcomes: "STCW VI/3 Advanced Fire Fighting Certificate\nNIMASA-registered\nFire plan interpretation\nFire team command\nLive fire exercises", nimasaApproved: true },
  { slug: "medical-care-onboard", title: "Medical Care Onboard", stcwRegulation: "STCW VI/4.2", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "STCW VI/4.2 Medical Care training for officers designated to provide medical care onboard. Covers diagnosis, treatment, use of telemedicine and medication management.", eligibility: "Deck or engineering officer\nValid BST or MFAU certificate\nAge 18+", outcomes: "STCW VI/4.2 Medical Care Certificate\nNIMASA-registered\nMedical diagnosis skills\nTelemedicine usage\nMedication management", nimasaApproved: true },
  { slug: "oow-deck-prep", title: "Officer of the Watch Deck (OOW Prep)", stcwRegulation: "STCW II/1", level: "POST_COC", durationWeeks: 12, feeNaira: 0, registrationFormType: "MS_FORM", description: "Intensive preparation course for officers seeking the OOW Deck STCW II/1 Certificate of Competency. Covers celestial navigation, COLREGS, passage planning and bridge watchkeeping.", eligibility: "Valid Cadet certificate or sea service record\nMinimum 12 months sea service\nMedical certificate", outcomes: "Preparation for STCW II/1 CoC examination\nNIMASA examination readiness\nCelestial navigation\nBridge simulator hours\nCOLREGS competency", nimasaApproved: true },
  { slug: "oow-engine-prep", title: "Officer of the Watch Engine (OOW Prep)", stcwRegulation: "STCW III/1", level: "POST_COC", durationWeeks: 12, feeNaira: 0, registrationFormType: "MS_FORM", description: "Intensive preparation for the OOW Engine STCW III/1 CoC examination. Covers diesel engine theory, electrical systems, auxiliary machinery and engine room watchkeeping.", eligibility: "Valid Engineering Cadet certificate or sea service\nMinimum 12 months sea service\nMedical certificate", outcomes: "Preparation for STCW III/1 CoC examination\nDiesel engine systems competency\nElectrical systems knowledge\nEngine room watchkeeping\nNIMASA examination readiness", nimasaApproved: true },
  { slug: "chief-mate-coc-prep", title: "Chief Mate (Unlimited) CoC Prep", stcwRegulation: "STCW II/2", level: "POST_COC", durationWeeks: 78, feeNaira: 0, registrationFormType: "MS_FORM", description: "Advanced preparation programme for experienced OOW Deck officers seeking Chief Mate STCW II/2 certification. Covers advanced navigation, cargo operations and vessel stability.", eligibility: "Valid OOW Deck CoC\nMinimum 12 months sea service as OOW\nMedical certificate", outcomes: "Chief Mate CoC (Unlimited)\nAdvanced navigation competency\nCargo and stability expertise\nCommand preparedness", nimasaApproved: true },
  { slug: "master-coc-class-2", title: "Master Mariner CoC Class 2", stcwRegulation: "STCW II/2", level: "POST_COC", durationWeeks: 26, feeNaira: 0, registrationFormType: "MS_FORM", description: "Preparation and assessment programme for experienced Chief Mates seeking the Master Mariner Class 2 Certificate of Competency. The highest deck officer qualification recognised by NIMASA.", eligibility: "Valid Chief Mate CoC\nMinimum 12 months sea service as Chief Mate\nMedical certificate\nAge 25+", outcomes: "Master Mariner CoC Class 2\nNIMASA-registered\nVessel command authority\nSafety management system competency\nISM Code compliance", nimasaApproved: true },
  { slug: "coc-revalidation-refresher", title: "CoC Revalidation (STCW Refresher)", stcwRegulation: "STCW Various", level: "REFRESHER", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Mandatory 5-year STCW revalidation refresher for officers whose Certificate of Competency is due for renewal. Covers STCW Manila amendments, BRM and safety management.", eligibility: "Valid or recently expired CoC\nProof of sea service\nMedical certificate", outcomes: "STCW revalidation endorsement\nUpdated Manila amendment competencies\nNIMASA certificate renewal", nimasaApproved: true },
  // VALUE-ADDED
  { slug: "vessel-steering-ror", title: "Vessel Steering and Rules of the Road (ROR)", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Practical training in vessel steering techniques and COLREGS (Rules of the Road) for deck officers and ratings. Includes bridge simulator sessions.", eligibility: "Deck officers and ratings\nAge 18+", outcomes: "ROR competency certificate\nCOLREGS mastery\nSteering techniques\nNIMASA-endorsed", nimasaApproved: true },
  { slug: "incident-investigation", title: "Maritime Incident Investigation", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Equips officers with skills to conduct onboard incident and accident investigations using root-cause analysis, ISM Code procedures and flag state reporting.", eligibility: "Officers and safety officers\nAge 18+", outcomes: "Incident investigation methodology\nRoot cause analysis\nISM Code compliance\nFlag state reporting", nimasaApproved: false },
  { slug: "risk-assessment", title: "Maritime Risk Assessment", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Formal maritime risk assessment techniques including HAZID, bow-tie analysis and permit-to-work systems for safety officers and officers of the watch.", eligibility: "Officers and safety officers\nAge 18+", outcomes: "Risk matrix methodology\nHAZID and bow-tie analysis\nPermit-to-work systems\nISM safety management", nimasaApproved: false },
  { slug: "psc-sire-inspection-prep", title: "PSC and SIRE 2.0 Inspection Preparation", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Comprehensive preparation for Port State Control and OCIMF SIRE 2.0 tanker inspections. Covers VIQ 7, deficiency management and best practice vessel presentation.", eligibility: "Officers on tankers or vessels subject to SIRE inspection\nAge 18+", outcomes: "SIRE 2.0 VIQ awareness\nPSC deficiency avoidance\nTanker inspection readiness\nOCIMF best practices", nimasaApproved: false },
  { slug: "ism-code", title: "ISM Code and Safety Management", stcwRegulation: null, level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "Understanding and implementing the International Safety Management (ISM) Code for officers, DPAs and vessel operators. SMS development, auditing and near-miss reporting.", eligibility: "Officers, DPAs, fleet managers\nAge 18+", outcomes: "ISM Code competency\nSMS development skills\nISM auditing methodology\nNear-miss reporting culture", nimasaApproved: false },
  { slug: "ship-security-officer", title: "Ship Security Officer (SSO)", stcwRegulation: "STCW VI/5", level: "SHORT_COURSE", durationWeeks: 1, feeNaira: 0, registrationFormType: "MS_FORM", description: "ISPS Code and STCW VI/5 compliant Ship Security Officer training. Security threat assessment, SSP implementation and security drills.", eligibility: "Current or aspiring deck officer\nBasic Safety Training certificate\nAge 18+", outcomes: "STCW VI/5 SSO Certificate\nISPS Code competency\nSecurity plan implementation\nNIMASA-registered certification", nimasaApproved: true },
  { slug: "port-shipping-management", title: "Port and Shipping Management Diploma", stcwRegulation: null, level: "POST_COC", durationWeeks: 52, feeNaira: 0, registrationFormType: "MS_FORM", description: "A one-year professional diploma in port operations, shipping economics, logistics and trade. Ideal for NPA, NIMASA and shipping company professionals.", eligibility: "Degree or HND in any discipline\nAge 21+\nWork experience preferred", outcomes: "Port Operations Certificate\nShipping economics competency\nNPA/NIMASA career readiness\nLogistics and trade expertise", nimasaApproved: false },
];

async function main() {
  const results = [];
  for (const c of courses) {
    try {
      const exists = await prisma.course.findUnique({ where: { slug: c.slug } });
      if (!exists) {
        await prisma.course.create({ data: { ...c, isActive: true } });
        results.push("CREATED: " + c.slug);
      } else {
        await prisma.course.update({ where: { slug: c.slug }, data: { registrationFormType: c.registrationFormType, feeNaira: 0 } });
        results.push("UPDATED: " + c.slug);
      }
    } catch (e) {
      results.push("ERROR " + c.slug + ": " + e.message);
    }
  }
  console.log(results.join("\n"));
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
