import type { VirInspectionTypeCategory } from "@prisma/client";
import type { VirTemplateImport } from "@/lib/vir/import";

export type VirInspectionTypeSeed = {
  code: string;
  name: string;
  category: VirInspectionTypeCategory;
  description: string;
};

export const VIR_SPEC_COUNTS = {
  claimedInspectionTypes: 54,
  extractedInspectionTypes: 59,
};

export const VIR_INSPECTION_TYPES: VirInspectionTypeSeed[] = [
  { code: "SIRE", name: "SIRE", category: "VETTING", description: "Standard OCIMF SIRE inspection workflow." },
  { code: "SIRE_2_0", name: "SIRE 2.0", category: "VETTING", description: "Structured SIRE 2.0 inspection and questionnaire handling." },
  { code: "CDI", name: "CDI (Chemical Distributor's Inspection)", category: "VETTING", description: "CDI inspection readiness and finding capture." },
  { code: "RIGHTSHIP", name: "Rightship", category: "VETTING", description: "RightShip inspection reporting and follow-up." },
  { code: "RIGHTSHIP_SELF", name: "Rightship Self", category: "VETTING", description: "Internal RightShip self-assessment before external boarding." },
  { code: "NON_SIRE", name: "Non-SIRE", category: "VETTING", description: "General third-party vetting outside standard SIRE workflows." },
  { code: "PRE_VETTING_INSPECTION", name: "Pre-Vetting Inspection", category: "VETTING", description: "Pre-arrival vetting readiness inspection." },
  { code: "PRE_VET_SELF", name: "Pre-Vet (Self)", category: "VETTING", description: "Shipboard self-check before a vetting event." },
  { code: "MASTERS_VETTING_SELF_ASSESSMENT", name: "Master's Vetting Self Assessment", category: "VETTING", description: "Master-led self-assessment ahead of charterer vetting." },
  { code: "OIL_MAJOR_ID", name: "Oil_Major_ID", category: "VETTING", description: "Oil major inspection or identification workflow." },
  { code: "IDLE_SIRE", name: "Idle SIRE", category: "VETTING", description: "SIRE inspection for laid-up or idle vessels." },
  { code: "IDLE_CDI", name: "Idle CDI", category: "VETTING", description: "CDI inspection for laid-up or idle vessels." },
  { code: "OVID", name: "OVID (Offshore Vessel Inspection DB)", category: "VETTING", description: "OVID-style offshore inspection workflow." },
  { code: "CHARTERERS_INSPECTION", name: "Charterer's Inspection", category: "VETTING", description: "Charterer inspection management and sign-off." },
  { code: "PORT_STATE_CONTROL", name: "Port State Control", category: "PSC", description: "PSC inspection with CIC highlighting and deficiency management." },
  { code: "PSC_SELF_ASSESSMENT", name: "PSC Self Assessment", category: "PSC", description: "Internal PSC preparation questionnaire and review." },
  { code: "FLAG_STATE_INSPECTION", name: "Flag State Inspection", category: "PSC", description: "Flag administration inspection workflow." },
  { code: "IMMIGRATION_CUSTOMS_INSPECTION", name: "Immigration / Customs Inspection", category: "PSC", description: "Arrival inspection for customs and immigration compliance." },
  { code: "MARPOL_INSPECTION", name: "MARPOL Inspection", category: "PSC", description: "Pollution prevention and MARPOL compliance inspection." },
  { code: "PORT_SAFETY_INSPECTION", name: "Port Safety Inspection", category: "PSC", description: "Port authority safety inspection workflow." },
  { code: "SANITATION_INSPECTION", name: "Sanitation Inspection", category: "PSC", description: "Sanitation and hygiene inspection management." },
  { code: "SECURITY_INSPECTION", name: "Security Inspection", category: "PSC", description: "Security or ISPS-focused boarding inspection." },
  { code: "TERMINAL_INSPECTION", name: "Terminal Inspection", category: "PSC", description: "Terminal-side readiness and compatibility inspection." },
  { code: "CLASS_SURVEY", name: "Class Survey", category: "CLASS", description: "Planned or ad hoc classification society survey." },
  { code: "DRY_DOCKING_INSPECTION", name: "Dry Docking Inspection", category: "CLASS", description: "Dry dock entry or progress inspection." },
  { code: "DRY_DOCKING_INSPECTION_EXTERNAL", name: "Dry Docking Inspection (External)", category: "CLASS", description: "Third-party dry dock inspection and review." },
  { code: "DAMAGE_REPAIR_INSPECTION", name: "Damage & Repair Inspection", category: "CLASS", description: "Inspection for casualty, damage, and repairs." },
  { code: "H_AND_M_INSPECTION", name: "H & M Inspection", category: "CLASS", description: "Hull and machinery insurer inspection workflow." },
  { code: "P_AND_I_INSPECTION", name: "P & I Inspection", category: "CLASS", description: "Protection and indemnity inspection workflow." },
  { code: "OFF_HIRE_SURVEY", name: "Off Hire Survey", category: "CLASS", description: "Condition survey at charter off-hire." },
  { code: "ON_HIRE_SURVEY", name: "On Hire Survey", category: "CLASS", description: "Condition survey at charter on-hire." },
  { code: "PRE_PURCHASE_INSPECTION", name: "Pre Purchase Inspection", category: "CLASS", description: "Technical due diligence before vessel purchase." },
  { code: "SEA_TRIAL", name: "Sea Trial", category: "CLASS", description: "Sea trial assessment and issue logging." },
  { code: "GAS_TRIAL", name: "Gas Trial", category: "CLASS", description: "Gas trial or cargo-system readiness validation." },
  { code: "OWNERS_INSPECTION_INTERNAL", name: "Owner's Inspection (Internal)", category: "INTERNAL", description: "Internal owner-driven vessel condition review." },
  { code: "QHSE_VISIT", name: "QHSE Visit", category: "INTERNAL", description: "Routine QHSE office visit to vessel." },
  { code: "GENERAL_OFFICE_VISIT", name: "General Office Visit", category: "INTERNAL", description: "General office inspection or support visit." },
  { code: "SENIOR_MANAGEMENT_VISIT", name: "Senior Management Visit", category: "INTERNAL", description: "Management walk-through with strategic review focus." },
  { code: "OPERATIONS_VISIT", name: "Operations Visit", category: "INTERNAL", description: "Operations department vessel visit and action tracking." },
  { code: "FLEET_PERFORMANCE_CENTRE_VISIT", name: "Fleet Performance Centre Visit", category: "INTERNAL", description: "Fleet performance benchmarking and review visit." },
  { code: "ENGINEERING_AUDIT", name: "Engineering Audit", category: "INTERNAL", description: "Internal engineering systems and maintenance audit." },
  { code: "ENGINEERING_AUDIT_EXTERNAL", name: "Engineering Audit (External)", category: "INTERNAL", description: "External engineering inspection with evidence review." },
  { code: "NAVIGATION_AUDIT_INTERNAL", name: "Navigation Audit (Internal)", category: "INTERNAL", description: "Internal bridge, navigation, and watchkeeping audit." },
  { code: "NAVIGATION_AUDIT_EXTERNAL", name: "Navigation Audit (External)", category: "INTERNAL", description: "External navigation audit and closeout tracking." },
  { code: "MOORING_AUDIT", name: "Mooring Audit", category: "INTERNAL", description: "Mooring equipment and procedure inspection." },
  { code: "SMS_SETUP", name: "SMS Setup", category: "INTERNAL", description: "Safety management setup or implementation review." },
  { code: "RAPID_VESSEL_INSPECTION", name: "Rapid Vessel Inspection", category: "INTERNAL", description: "Short-form rapid review for high-priority issues." },
  { code: "MASTERS_TAKEOVER_INSPECTION", name: "Master's Takeover Inspection", category: "INTERNAL", description: "Formal handover inspection for incoming master." },
  { code: "CHIEF_ENGINEERS_TAKEOVER_INSPECTION", name: "Chief Engineer's Takeover Inspection", category: "INTERNAL", description: "Formal handover inspection for incoming chief engineer." },
  { code: "MASTERS_NAVIGATIONAL_ASSESSMENT", name: "Master's Navigational Assessment", category: "INTERNAL", description: "Navigational assessment led by or for the master." },
  { code: "REMOTE_NAVIGATIONAL_ASSESSMENT", name: "Remote Navigational Assessment", category: "INTERNAL", description: "Remote navigation assurance review." },
  { code: "ISM_ISPS_MLC_ISO_AUDIT_EXTERNAL", name: "ISM / ISPS / MLC / ISO Audit (External)", category: "AUDIT", description: "Integrated external audit across core management systems." },
  { code: "ENVIRONMENTAL_AUDIT", name: "Environmental Audit", category: "AUDIT", description: "Environmental compliance and performance audit." },
  { code: "ENVIRONMENTAL_INSPECTION_EXTERNAL", name: "Environmental Inspection (External)", category: "AUDIT", description: "External environmental inspection and findings review." },
  { code: "ISO_9001_INSPECTION", name: "ISO 9001 Inspection", category: "AUDIT", description: "Quality management inspection aligned to ISO 9001." },
  { code: "ISO_14001_INSPECTION", name: "ISO 14001 Inspection", category: "AUDIT", description: "Environmental management inspection aligned to ISO 14001." },
  { code: "ISO_45001_INSPECTION", name: "ISO 45001 Inspection", category: "AUDIT", description: "Occupational health and safety inspection aligned to ISO 45001." },
  { code: "ISO_50001_INSPECTION", name: "ISO 50001 Inspection", category: "AUDIT", description: "Energy management inspection aligned to ISO 50001." },
  { code: "ISO_27001_INSPECTION", name: "ISO 27001 Inspection", category: "AUDIT", description: "Cyber and information security inspection aligned to ISO 27001." },
];

export const VIR_IMPLEMENTATION_PHASES = [
  {
    phase: "Phase 1",
    title: "Foundation",
    outcome: "Vessel master, inspection type master, questionnaire template engine, seed data, and dry-run import validation.",
  },
  {
    phase: "Phase 2",
    title: "Operational Workflow",
    outcome: "Inspection creation, answers, findings, corrective actions, carryover, and shore sign-off gate.",
  },
  {
    phase: "Phase 3",
    title: "AI Import",
    outcome: "PDF upload, extraction pipeline, confidence review, audit trail, and commit-to-draft workflow.",
  },
  {
    phase: "Phase 4",
    title: "Analytics & Mobile",
    outcome: "Dashboard, exports, offline/PWA support, and vessel-side tablet optimization.",
  },
];

export const VIR_SAMPLE_TEMPLATE_PAYLOAD: VirTemplateImport = {
  inspectionTypeCode: "PORT_STATE_CONTROL",
  inspectionTypeName: "Port State Control",
  inspectionCategory: "PSC",
  templateName: "PSC Self-Assessment Starter",
  version: "2026.1",
  description: "Starter PSC questionnaire showing mandatory, risk-scored, and CIC-sensitive questions.",
  sections: [
    {
      code: "CERTS",
      title: "Certificates & Readiness",
      guidance: "Confirm statutory and trading certificates are onboard, valid, and presented correctly.",
      questions: [
        {
          code: "CERTS-001",
          prompt: "Are all statutory certificates valid, signed, and available for review?",
          responseType: "YES_NO_NA",
          riskLevel: "CRITICAL",
          isMandatory: true,
          allowsObservation: true,
          allowsPhoto: true,
          isCicCandidate: true,
          cicTopic: "Certification",
        },
        {
          code: "CERTS-002",
          prompt: "Enter the number of certificates expiring within the next 30 days.",
          responseType: "NUMBER",
          riskLevel: "HIGH",
          isMandatory: true,
          allowsObservation: true,
          allowsPhoto: false,
        },
      ],
    },
    {
      code: "FIRE",
      title: "Fire Safety",
      guidance: "Validate operational readiness of fire detection, pumps, and emergency organization.",
      questions: [
        {
          code: "FIRE-001",
          prompt: "Fire pump pressure and hydrant test status",
          responseType: "SINGLE_SELECT",
          riskLevel: "HIGH",
          isMandatory: true,
          allowsObservation: true,
          allowsPhoto: true,
          options: [
            { value: "SATISFACTORY", label: "Satisfactory", score: 100 },
            { value: "MINOR_ISSUE", label: "Minor issue", score: 60 },
            { value: "UNSATISFACTORY", label: "Unsatisfactory", score: 0 },
          ],
        },
        {
          code: "FIRE-002",
          prompt: "Describe any impairment or bypass active on the fire detection system.",
          responseType: "TEXT",
          riskLevel: "HIGH",
          isMandatory: false,
          allowsObservation: true,
          allowsPhoto: true,
          isCicCandidate: true,
          cicTopic: "Fire safety systems",
        },
      ],
    },
    {
      code: "NAV",
      title: "Navigation",
      guidance: "Assess bridge readiness, publications, and watchkeeping discipline.",
      questions: [
        {
          code: "NAV-001",
          prompt: "Is the passage plan current, berth-to-berth, and signed by the bridge team?",
          responseType: "YES_NO_NA",
          riskLevel: "HIGH",
          isMandatory: true,
          allowsObservation: true,
          allowsPhoto: true,
          isCicCandidate: true,
          cicTopic: "Passage planning",
        },
        {
          code: "NAV-002",
          prompt: "Bridge publications update date",
          responseType: "DATE",
          riskLevel: "MEDIUM",
          isMandatory: false,
          allowsObservation: false,
          allowsPhoto: false,
        },
        {
          code: "NAV-003",
          prompt: "Which equipment issues are currently affecting navigation readiness?",
          responseType: "MULTI_SELECT",
          riskLevel: "HIGH",
          isMandatory: false,
          allowsObservation: true,
          allowsPhoto: true,
          options: [
            { value: "ECDIS", label: "ECDIS" },
            { value: "RADAR", label: "RADAR" },
            { value: "GYRO", label: "Gyro" },
            { value: "BNWAS", label: "BNWAS" },
          ],
        },
      ],
    },
  ],
};
